"""add_fk_cascade_constraints

Revision ID: f1e29dd920d2
Revises: cc760d2942d1
Create Date: 2026-04-22 13:07:43.575820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e29dd920d2'
down_revision: Union[str, Sequence[str], None] = 'cc760d2942d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('allocations_portfolio_id_fkey'), 'allocations', type_='foreignkey')
    op.drop_constraint(op.f('allocations_asset_class_id_fkey'), 'allocations', type_='foreignkey')
    op.create_foreign_key(None, 'allocations', 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'allocations', 'asset_classes', ['asset_class_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('portfolios_user_id_fkey'), 'portfolios', type_='foreignkey')
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.create_foreign_key(op.f('portfolios_user_id_fkey'), 'portfolios', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'allocations', type_='foreignkey')
    op.drop_constraint(None, 'allocations', type_='foreignkey')
    op.create_foreign_key(op.f('allocations_asset_class_id_fkey'), 'allocations', 'asset_classes', ['asset_class_id'], ['id'])
    op.create_foreign_key(op.f('allocations_portfolio_id_fkey'), 'allocations', 'portfolios', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###
